// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class All_Tables_insertion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(All_Tables_insertion));
        
        string IMigrationMetadata.Id
        {
            get { return "202301161952176_All_Tables_insertion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
