//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT_ASSIGNMENT_3.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public Courses()
        {
            this.CourseStudents = new HashSet<CourseStudents>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PreReq { get; set; }
    
        public virtual ICollection<CourseStudents> CourseStudents { get; set; }
    }
}
