//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingwithme.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int p_ID { get; set; }
        public string p_Name { get; set; }
        public double p_Price { get; set; }
        public int p_Qty { get; set; }
        public int p_how_many { get; set; }
    }
}
