//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT_ASSIGNMENT_2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkoutlist
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Qty { get; set; }
        public int Total_Cost { get; set; }
    }
}
