//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restrurant
    {
        public string Name { get; set; }
        public int res_id { get; set; }
        public string storate_time { get; set; }
        public int Food_typeid { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
